name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - "*"

variables:
  isMainBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isTestBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/test')]
  isDevBranch: $[and(ne(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.SourceBranch'],'refs/heads/test'))]

stages:
  - stage: SetEnvVars
    jobs:
      - template: pipelines/set-env-variables-job.yml
        parameters:
          environment: $(environment)
          env_url: $(env_url)

  - stage: Dev
    dependsOn: SetEnvVars
    condition: and(succeeded(), eq(variables['isDevBranch'], true))
    jobs:
      - template: pipelines/build-deploy-job.yml
        parameters:
          environment: dev

  - stage: Test
    dependsOn: Dev
    condition: and(succeeded(), eq(variables['isTestBranch'], true))
    jobs:
      - template: pipelines/build-deploy-job.yml
        parameters:
          environment: test

  - stage: Prod
    dependsOn: Test
    condition: and(succeeded(), eq(variables['isMainBranch'], true))
    jobs:
      - template: pipelines/build-deploy-job.yml
        parameters:
          environment: prod
