parameters:
  - name: environment
    type: string

jobs:
- job: build_and_deploy
  displayName: 'Build and Deploy to ${{ parameters.environment }}'
  dependsOn: ['set_env_vars', 'unit_tests']
  pool:
    vmImage: ubuntu-latest
  variables:
    - group: Azure-Static-Web-Apps-agreeable-dune-0c6e15e00-variable-group
    
    - name: NUXT_PUBLIC_ENV_URL
      value: $[dependencies.set_env_vars.outputs['setVariable.NUXT_PUBLIC_ENV_URL']] 
   
    - name: NUXT_AAD_ENDPOINT_BASE
      value: $[dependencies.set_env_vars.outputs['setVariable.NUXT_AAD_ENDPOINT_BASE']] 

    - name: NUXT_TENANT_ID
      value: $[dependencies.set_env_vars.outputs['setVariable.NUXT_TENANT_ID']]

    - name: NUXT_CLIENT_ID
      value: $[dependencies.set_env_vars.outputs['setVariable.NUXT_CLIENT_ID']]  
    
    - name: NUXT_CLIENT_SECRET
      value: $[dependencies.set_env_vars.outputs['setVariable.NUXT_CLIENT_SECRET']]  

  steps:
    - checkout: self
      submodules: true
      
    - script: |
        echo "NUXT_PUBLIC_ENV_URL: $(NUXT_PUBLIC_ENV_URL)"
        echo "NUXT_AAD_ENDPOINT_BASE: $(NUXT_AAD_ENDPOINT_BASE)"
        echo "NUXT_TENANT_ID: $(NUXT_TENANT_ID)"
        echo "NUXT_CLIENT_ID: $(NUXT_CLIENT_ID)"
        echo "NUXT_CLIENT_SECRET: $(NUXT_CLIENT_SECRET)"
      displayName: 'Print environment variables for debugging'
    - task: AzureStaticWebApp@0
      inputs:
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_DUNE_0C6E15E00)
        app_location: "/" # App source code path
        api_location: ".output/server" # Api source code path - optional
        output_location: ".output/public" # Built app content directory - optional
        verbose: true
        production_branch: 'main'
