  
jobs:
  - job: unit_tests
    displayName: Run Unit Tests
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Azure-Static-Web-Apps-agreeable-dune-0c6e15e00-variable-group
    steps:
      - checkout: self
        submodules: true
      - template: set-env-variables-job.yml
      - task: NodeTool@0
        inputs:
          versionSpec: 20.x
      - bash: |
          npm install
          npm run test:unit
