parameters:
  - name: environment
    type: string
    
jobs:
  - job: set_env_vars
    displayName: "Set Environment Variables for ${{ parameters.environment }}"
    pool:
      vmImage: ubuntu-latest
    variables:
      - group: Azure-Static-Web-Apps-agreeable-dune-0c6e15e00-variable-group
    steps:
      - script: |
          ENV_URL_VAR="ENV_URL_${{ parameters.environment }}"
          NUXT_PUBLIC_ENV_URL=$(eval echo \$$ENV_URL_VAR)
          
          echo "##vso[task.setvariable variable=NUXT_PUBLIC_ENV_URL;isOutput=true]$NUXT_PUBLIC_ENV_URL"
          echo "##vso[task.setvariable variable=NUXT_AAD_ENDPOINT_BASE;isOutput=true;]$(AAD_ENDPOINT_BASE)"
          echo "##vso[task.setvariable variable=NUXT_TENANT_ID;isOutput=true;]$(TENANT_ID)"
          echo "##vso[task.setvariable variable=NUXT_CLIENT_ID;isOutput=true;]$(CLIENT_ID)"
          echo "##vso[task.setvariable variable=NUXT_CLIENT_SECRET;isOutput=true;]$(CLIENT_SECRET)"
        displayName: "Set environment variables"
